FROM registry-vpc.cn-hangzhou.aliyuncs.com/thundersdata-public/nginx:1.17.2
MAINTAINER thundersdata.com
VOLUME /tmp
ENV LANG en_US.UTF-8
RUN echo "server {  \
                    listen       8888; \
                    location / { \
                        root   /var/www/html/; \
                        index  index.html index.htm; \
                        flv_live on;
                        chunked_transfer_encoding on;
                        add_header Access-Control-Allow-Origin *;\
                        add_header Access-Control-Allow-Credentials 'true';
                    } \
                  access_log  /var/log/nginx/access.log ; \
              } " > /etc/nginx/conf.d/default.conf \
    &&  mkdir  -p  /var/www \
    &&  mkdir -p /var/www/html

ADD build/ /var/www/html/
EXPOSE 80
EXPOSE 443